// UCS(Universal Category System) CatID → [Category, SubCategory]
// SFX 라이브러리(Boom, Sound Ideas 등)는 파일명이 `CatID_FXName_CreatorID_SourceID`.
// 첫 토큰(CatID)을 카테고리/서브카테고리로 해석. 자주 쓰이는 CatID 위주로 매핑.
const UCS_CATID: Record<string, [string, string]> = {
  AIRBrst: ['AIR', 'Burst'],
  AIRHiss: ['AIR', 'Hiss'],
  AMBDsgn: ['AMBIENCE', 'Designed'],
  AMBNat: ['AMBIENCE', 'Nature'],
  AMBUrb: ['AMBIENCE', 'Urban'],
  AMBRur: ['AMBIENCE', 'Rural'],
  AMBTone: ['AMBIENCE', 'Tone'],
  ANMLDom: ['ANIMAL', 'Domestic'],
  ANMLWild: ['ANIMAL', 'Wild'],
  BELLHnd: ['BELL', 'Handbell'],
  BELLLrg: ['BELL', 'Large'],
  BRSTGen: ['BURST', 'General'],
  BULLImpt: ['BULLET', 'Impact'],
  CERAImpt: ['CERAMIC', 'Impact'],
  CHRSGen: ['CHARACTER', 'General'],
  CLOTH: ['CLOTH', 'Movement'],
  CLTHMvmt: ['CLOTH', 'Movement'],
  COMPBeep: ['COMPUTER', 'Beep'],
  COMPUI: ['COMPUTER', 'UI'],
  CROWD: ['CROWD', 'General'],
  CRWDReac: ['CROWD', 'Reaction'],
  DESGN: ['DESIGNED', 'General'],
  DSGN: ['DESIGNED', 'General'],
  DSGNImpt: ['DESIGNED', 'Impact'],
  DSGNSynth: ['DESIGNED', 'Synthetic'],
  DSGNWhsh: ['DESIGNED', 'Whoosh'],
  DSGNDron: ['DESIGNED', 'Drone'],
  DSGNRise: ['DESIGNED', 'Riser'],
  DSGNGlitch: ['DESIGNED', 'Glitch'],
  DSGNText: ['DESIGNED', 'Texture'],
  DOOR: ['DOOR', 'General'],
  DOORWod: ['DOOR', 'Wood'],
  DOORMtl: ['DOOR', 'Metal'],
  DRONGen: ['DRONE', 'General'],
  ELECHum: ['ELECTRICITY', 'Hum'],
  ELECSpk: ['ELECTRICITY', 'Spark'],
  EXPLDsgn: ['EXPLOSION', 'Designed'],
  EXPLReal: ['EXPLOSION', 'Real'],
  FIREBrn: ['FIRE', 'Burn'],
  FIREGen: ['FIRE', 'General'],
  FOOTMtl: ['FOOTSTEP', 'Metal'],
  FOOTWod: ['FOOTSTEP', 'Wood'],
  FOOTConc: ['FOOTSTEP', 'Concrete'],
  FOOT: ['FOOTSTEP', 'General'],
  FOLYGen: ['FOLEY', 'General'],
  FOLYProp: ['FOLEY', 'Prop'],
  GLASBrk: ['GLASS', 'Break'],
  GLASImpt: ['GLASS', 'Impact'],
  GORE: ['GORE', 'General'],
  GUNAuto: ['GUN', 'Automatic'],
  GUNHand: ['GUN', 'Handgun'],
  GUNShot: ['GUN', 'Shot'],
  GUNMech: ['GUN', 'Mechanism'],
  HORN: ['HORN', 'General'],
  IMPTMtl: ['IMPACT', 'Metal'],
  IMPTWod: ['IMPACT', 'Wood'],
  IMPTGen: ['IMPACT', 'General'],
  IMPT: ['IMPACT', 'General'],
  LASR: ['LASER', 'General'],
  LIQDGen: ['LIQUID', 'General'],
  MAGSpell: ['MAGIC', 'Spell'],
  MAGGen: ['MAGIC', 'General'],
  MECHGen: ['MECHANICAL', 'General'],
  METLImpt: ['METAL', 'Impact'],
  METLScr: ['METAL', 'Scrape'],
  MUSCStg: ['MUSIC', 'Sting'],
  MUSCLoop: ['MUSIC', 'Loop'],
  MUSC: ['MUSIC', 'General'],
  PAPRGen: ['PAPER', 'General'],
  PLSTImpt: ['PLASTIC', 'Impact'],
  RAIN: ['RAIN', 'General'],
  RICO: ['RICOCHET', 'General'],
  ROCK: ['ROCK', 'General'],
  SCIFI: ['SCIFI', 'General'],
  SCIComp: ['SCIFI', 'Computer'],
  SPRTGen: ['SPORTS', 'General'],
  STING: ['STINGER', 'General'],
  SWSH: ['SWOOSH', 'General'],
  SWTCH: ['SWITCH', 'General'],
  TOOL: ['TOOL', 'General'],
  TOON: ['CARTOON', 'General'],
  UI: ['UI', 'General'],
  UICl: ['UI', 'Click'],
  UIBeep: ['UI', 'Beep'],
  VEHCar: ['VEHICLE', 'Car'],
  VEHGen: ['VEHICLE', 'General'],
  VOXShout: ['VOICE', 'Shout'],
  VOX: ['VOICE', 'General'],
  WATRGen: ['WATER', 'General'],
  WEAPImpt: ['WEAPON', 'Impact'],
  WHSHGen: ['WHOOSH', 'General'],
  WHSH: ['WHOOSH', 'General'],
  WHOOSH: ['WHOOSH', 'General'],
  WIND: ['WIND', 'General'],
  WOOD: ['WOOD', 'General'],
  WHSTL: ['WHISTLE', 'General']
}

/** 파일명에서 UCS CatID를 해석해 [카테고리, 서브카테고리] 반환 (실패 시 null) */
export function categoryFromFilename(filename: string): { category: string; subcategory: string } | null {
  const base = filename.replace(/\.[^.]+$/, '')
  const catId = base.split('_')[0]
  if (!catId) return null
  const hit = UCS_CATID[catId]
  if (hit) return { category: hit[0], subcategory: hit[1] }
  // 정확 매칭 실패 시: 앞 4글자로 대분류만 추정 (예: DSGN..., FOOT..., IMPT...)
  const prefixMap: Record<string, string> = {
    DSGN: 'DESIGNED',
    DESG: 'DESIGNED',
    IMPT: 'IMPACT',
    FOOT: 'FOOTSTEP',
    AMB: 'AMBIENCE',
    EXPL: 'EXPLOSION',
    GUN: 'GUN',
    WHSH: 'WHOOSH',
    WHOO: 'WHOOSH',
    METL: 'METAL',
    GLAS: 'GLASS',
    DOOR: 'DOOR',
    FIRE: 'FIRE',
    WATR: 'WATER',
    VEH: 'VEHICLE',
    SCI: 'SCIFI',
    MAG: 'MAGIC',
    UI: 'UI',
    MUSC: 'MUSIC',
    STING: 'STINGER',
    VOX: 'VOICE',
    ANML: 'ANIMAL',
    CROWD: 'CROWD',
    CRWD: 'CROWD'
  }
  for (const p of Object.keys(prefixMap).sort((a, b) => b.length - a.length)) {
    if (catId.toUpperCase().startsWith(p)) return { category: prefixMap[p], subcategory: '' }
  }
  return null
}
